-- =============================================
-- DEPRECADO — NO USAR ESTE ARCHIVO
-- =============================================
-- El template canónico para crear la BD de un venue nuevo es:
--
--     sql/venue_template.sql
--
-- Este archivo era una versión ANTERIOR del esquema (enum order_status sin
-- payment_authorized/payment_failed/checked_in, orders sin approved_by/
-- rejected_by, guest_list_signups sin rejected_at...). La BD viva de
-- 511 Events se creó con esta versión vieja, y de esa divergencia salieron
-- varios bugs de "columna fantasma" (ver reauditoría 2026-07-20/21 y
-- HANDOFF.md).
--
-- Reglas desde 2026-07-21:
--   1. Venues NUEVOS → ejecutar sql/venue_template.sql (completo).
--   2. El CÓDIGO no debe asumir columnas que no estén en la BD viva de 511
--      (la más pobre): trazabilidad tipo approved_by/rejected_by va en
--      metadata (jsonb), no en columnas.
--   3. Si venue_template.sql cambia, verificar el diff contra la BD viva
--      antes de tocar handlers.
-- =============================================
