-- =============================================
-- DEPRECADO — usar sql/venue_template.sql
-- =============================================
-- Historia: ESTE archivo era el esquema con el que se creó la BD viva de
-- 511 Events. El 2026-07-21 su contenido (verificado idéntico a la BD viva
-- columna a columna) se movió a sql/venue_template.sql como canónico único,
-- añadiendo las migraciones manuales posteriores (enum order_status completo
-- + staff_push_tokens). El archivo que antes se llamaba venue_template.sql
-- describía un esquema que no coincidía ni con la BD viva ni con el código
-- (origen de los bugs de "columna fantasma") y fue reemplazado.
--
-- Venues nuevos → ejecutar sql/venue_template.sql entero.
-- =============================================
